<?php
 

 /**
 * Implements hook_menu().
 */
 function twilio_sms_menu() {
  $items = array();
  $items['admin/config/workflow/rules/sms_action'] = array(
    'title' => 'Twilio Configuration',
    'description' => 'Set Twilio API settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('twilio_sms_settings'),
    'access arguments' => array('administer site configuration'),
   );
  return $items;
}

function twilio_sms_settings() {
    $form = array();

    $form['twilio_sid'] = array(
        '#type' => 'textfield',
        '#title' => t('account sid'),
        '#default_value' => variable_get('twilio_sid'),
        '#size' => 40,
        '#maxlength' => 255,
        '#required' => true,
        '#description' => t('twilio account sid - the 34 character string beginning with ac'),
    );
    $form['twilio_auth_token'] = array(
        '#type' => 'textfield',
        '#title' => t('auth token'),
        '#default_value' => variable_get('twilio_auth_token'),
        '#size' => 40,
        '#maxlength' => 255,
        '#required' => true,
        '#description' => t('twilio auth token - <a href="https://www.twilio.com/user/account">available on your dashboard</a>'),
    );
    $form['twilio_number'] = array(
        '#type' => 'textfield',
        '#title' => t('twilio number'),
        '#default_value' => variable_get('twilio_number'),
        '#size' => 40,
        '#maxlength' => 255,
        '#required' => true,
        '#description' => t('a <a href="https://www.twilio.com/user/account/phone-numbers" target="_new">phone number</a> from your twilio account'),
    );

    return system_settings_form($form);
}

/**
 * implements hook_node_validate().
 */
 function twilio_sms_node_validate($node, $form, &$form_state) {

    if($node->type != 'message') return;
    if (!isset($node->field_recipient_s_) || !isset($node->field_send_sms)) return;

    if (count($node->field_recipient_s_['und']) > 1 && $node->field_send_sms['und'][0]['value'] == 1) {
      form_set_error('send sms', t('sms option only available when there is one recipient...'));
    }
}

/**
 * implements hook_rules_action_info().
 */
function twilio_sms_rules_action_info() {
    return array(
        'twilio_sms_action_send_sms' => array(
            'label' => t('Sends a twilio SMS'),
            'group' => t('Twilio SMS'),
            'parameter' => array(
                'user' => array(
                    'type' => 'user',
                    'label' => t('Recipient'),
                ),
                'message' => array(
                    'type' => 'text',
                    'label' => t('Message'),
                ),
            ),
        ),
    );
}
 

function twilio_sms_action_send_sms($user, $message) {
    if (count($user->field_cell_phone) < 1) {
        drupal_set_message(t('the recipient has no cell phone!'), 'error');
        return;
    }

    $file = drupal_root . '/sites/all/libraries/twilio/twilio.php';
    if (!is_file($file)) {
        drupal_set_message(t('sms error, please contact the assassin manager staff for help.'), 'error');
        return;
    }

    require_once $file;

    $sid = variable_get('twilio_sid');
    $token = variable_get('twilio_auth_token');
    $recipient_phone = $user->field_cell_phone['und'][0]['value'];

    $client = new services_twilio($sid, $token);
    $message = $client->account->sms_messages->create(
        variable_get('twilio_number'),
        $recipient_phone,
        $message
    );

    print $message->sid;
}
