<?php

/* Block functions */

// implements hook_block_info().
function message_to_all_block_info() {
    $blocks = array();
    $blocks['message_to_all_block'] = array(
        'info' => t('Message to all users'),
    );
 
    return $blocks;
}

// implements hook_block_configure().
function message_to_all_block_configure($delta='') {
    return array();
}

// implements hook_block_view().
function message_to_all_block_view($delta='') {
  $block = array();
 
  switch($delta) {
    case 'message_to_all_block' :
        $block['subject'] = t('Message all users');
        $block['content'] = drupal_get_form('message_to_all_form');
        break;
    }
 
    return $block;
}

function message_to_all_form() {
    /* -- Message Form -- */
    $form['message_checkbox'] = array(
        '#type' => 'checkbox',
        '#title' => t('Show message box'),
    );

    $form['message'] = array(
        '#type' => 'container',
        '#states' => array(
            'visible' => array(
                ':input[name="message_checkbox"]' => array('checked' => TRUE),
                ),
            ),
    );

    $form['message']['subject_field'] = array(
        '#type' => 'textfield',
        '#title' => t('Subject:'),
        '#default_value' => '',
        '#size' => 30,
        '#maxlength' => 60,
    );

    $form['message']['message_field'] = array(
        '#type' => 'textarea',
        '#title' => t('Message'),
        '#wysiwyg' => false,
        '#rows' => 3,
    );

    $form['message']['message_send'] = array(
        '#type' => 'button', 
        '#name' => 'download',
        '#value' => t('Send message'),
        '#button_type' => 'submit',
        '#executes_submit_callback' => TRUE,
        '#submit' => array('send_message'),
    );

    return $form;
}

function message_to_all_form_validate(&$form, &$form_state) {
    if($form_state['values']['subject_field'] == "" || strlen($form_state['values']['subject_field']) == 0) {
        form_set_error('subject_field', t('Must enter subject'));
    }
    if($form_state['values']['message_field'] == "" || strlen($form_state['values']['message_field']) == 0) {
        form_set_error('message_field', t('Must enter message'));
    }
}


/* Form Doing functions */
function get_user_ids() {

    $query = db_select('users', 'u')
        ->fields('u', array('uid'))
        ->condition('status', '1')
        ->execute();

    $uids = array();
    while($record = $query->fetch()) {
        $target_id = array ('target_id' => $record->uid);
        array_push($uids, $target_id);
    }

    return $uids;
}

function send_message(&$form, &$form_state) {
    $node = new stdClass();
    $node->type = 'messages';
    node_object_prepare($node);

    $node->title = $form_state['values']['subject_field'];
    $node->field_body = $form_state['values']['message_field'];

    $node->field_recipient_s_['und'] = get_user_ids();

    node_save($node);
}